### ISSUE TITLE
Unexpected unit

### ISSUE THREAD

**Issue by margittennosaar** [CodeLaMat/tasteIT#3]
https://github.com/CodeLaMat/tasteIT/blob/075a5d0ea65f63155a11d437a74cb6995b13e220/src/components/Add.module.css#L108

Instead of **a { top: 0px }** use **a { top: 0 }**

**Comment by CodeLaMat** [comment]
Hi,
Did I get it right that, I need to remove **px** in this line and refactor it as (box-shadow: 0 14px 56px -11px #1875ff; )?

Because the issue note and the line does not match. 

Best,
Eyvaz

**Comment by CodeLaMat** [comment]
removed px
